import type { Metadata } from "next";
import "./globals.css";
import ConnectWallet from "../components/ConnectWallet";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en" suppressHydrationWarning>
  <body className={"antialiased font-sans"}>
        {/* Global Navbar */}
        <header className="sticky top-0 z-20 bg-background/80 backdrop-blur border-b border-white/10">
          <div className="mx-auto max-w-7xl px-6 md:px-10 py-4 flex items-center justify-between">
            <Link href="/" className="flex items-center gap-3">
              <div className="size-8 rounded-md bg-cta" />
              <div className="h5-space-mono text-[22px]">AI Agent Marketplace</div>
            </Link>
            <nav className="hidden md:flex items-center gap-6 h5-work-sans text-[16px]">
              <Link className="hover:opacity-80" href="/marketplace">Marketplace</Link>
              <Link className="hover:opacity-80" href="/#creators">Rankings</Link>
              <Link className="hover:opacity-80" href="/#how">How it works</Link>
              <ConnectWallet />
            </nav>
            <button className="md:hidden inline-flex items-center justify-center size-10 rounded-[14px] bg-[var(--background-secondary)]">
              <span className="sr-only">Menu</span>
              <div className="w-5 h-0.5 bg-white mb-1.5" />
              <div className="w-5 h-0.5 bg-white" />
            </button>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
